### ISSUE TITLE
Pyodide build fails

### ISSUE THREAD

**Issue by dr-vortex** [jprendes/emception#10]
See later part of #8 

![image](https://user-images.githubusercontent.com/75621402/197888140-9b198c9e-4f84-47ba-9e90-408e1a0975fb.png)

As you can see, the repo is on the latest commit but doesn't work still.

**Comment by jprendes** [comment]
I should have mentioned that you need to delete upstream/pyodide before re-running the script.

**Comment by dr-vortex** [comment]
Thanks
