### ISSUE TITLE
Pyodide and PythonProcess errors

### ISSUE THREAD

**Issue by dr-vortex** [jprendes/emception#11]
System (VM):
Ubuntu 22.04 LTS
27.4 GiB of Memory
i7-10700F Processor

Steps to reproduce:
- Clone Emception locally
- run `sudo ./build-with-docker.sh`
- copy build `cp -r emception/build/emception .`
- open index.html (I used Apache over localhost)
- Error occurs

[emception.log](https://github.com/jprendes/emception/files/10051001/emception.log)

**Comment by dr-vortex** [comment]
@jprendes 

May using a hardcoded commit id for the git clone/checkout of pyodide will fix it?

**Comment by jprendes** [comment]
The latest versions use cpython rather than pyodide, I would recommend you try with that.
The cpython build scripts were kind of broken until recently, but they should be fixed now.
Locally I can build and run the latest commit without problems.

**Comment by jprendes** [comment]
Closing this issue as I believe it is now fixed.
