### ISSUE TITLE
[Question] Permission to use code?

### ISSUE THREAD

**Issue by Johnn333** [jprendes/emception#13]
Hi @jprendes just wondering if we have permission to use this code in other projects? Interested in using the llvm-box, to compile code for embedded devices and this seems like a great start :)

**Comment by jprendes** [comment]
Hi Johnn,
Please feel free to use it.
Would something like MIT or Apache license work for you?

**Comment by Johnn333** [comment]
Thank you very much, MIT would work great if you are okay with that?

**Comment by Sinzolo** [comment]
Hey @jprendes, I've been looking at using this repo and it would be super handy for me too if you could add the license? Like @Johnn333, MIT would work for me. Would you like me to add a pull request for it? Thanks.

**Comment by jprendes** [comment]
I just added a license.
The license is `MIT OR Apache-2.0`.

**Comment by Sinzolo** [comment]
Perfect, thank you very much!
