### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by dr-vortex** [jprendes/emception#8]
The LLVM part of the build fails when building CXX object tools/clang/lib/AST/CMakeFiles/obj.clangAST.dir/Interp/Disasm.cpp.o, see the screenshot for more details.

![image](https://user-images.githubusercontent.com/75621402/197182939-de87b880-b81d-4e05-b4ef-6d056cdc1308.png)

Ran on Ubuntu 22.04.1 (LTS).
Ran using `sudo ./build-with-docker.sh`

**Comment by jprendes** [comment]
It looks like the compiler process was externally killed with SIGKILL.
I agree with @pmp-p that it might be the OOM killer.

**Comment by dr-vortex** [comment]
@jprendes @pmp-p 

The VM has 8 GiB of RAM and 3 cores with a 2.9 GHz base and 4.8 GHz boost.

**Comment by jprendes** [comment]
8 GiB is rather low for building LLVM.
I would try with at least 32 GiB.

**Comment by dr-vortex** [comment]
I have 32, so I'll try that.

**Comment by dr-vortex** [comment]
![image](https://user-images.githubusercontent.com/75621402/197304521-b8e4182a-de80-4695-8f0b-4cf400651be1.png)

Gave it 30 GB of memory, but now it's failing at pyodide (though not from memory).

**Comment by pmp-p** [comment]
tbh, you should try stock cpython, 3.11+ allows for wasm builds and build system is way simpler.

**Comment by jprendes** [comment]
It looks like the zlib version required by cpython in the pinned version of pyodide is not available in zlib.net anymore.

**Comment by jprendes** [comment]
With the [latest commit](https://github.com/jprendes/emception/commit/26196f4ca91c30773ab4848141bf5e20dae9f73d) I've updated the version of pyodide to use a version zlib available online.

It does build for me now.
I'm closing the issue, please do let me know if you encounter any other issue.
